name = "gyan-bharti-school"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-12-01"

[site]
bucket = "./dist"
entry-point = "./.cloudflare/workers-site"

[build]
command = "node build.js"
upload.format = "service-worker" 