// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyznkxeoowndztuwknzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5em5reGVvb3duZHp0dXdrbnptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDY2MDAsImV4cCI6MjA2NTAyMjYwMH0.YkGTwvyrPK4Dd1SkIMIS4LgKvyjCsMmsufO5MD5jJMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);